version: '3.8'

services:
  django_gunicorn:
    restart: always
    volumes:
      - static:/static
      - media:/media
      
    container_name: django_gunicorn
    env_file:
      - ./.env
    build:
      context: ./
    ports:
      - 8000:8000
    depends_on:
      - db

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - django_gunicorn

  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static:
  postgres_data:
  media:
